### ISSUE TITLE
Wykład 2 - strzałki

### ISSUE THREAD

**Issue by cieplinski-tobiasz** [PawelBogdan/bsk_lecture_notes#1]
Wydaję mi się, że w pliku authentication.py paragrafy "Obserwacja Denninga i Sacco" i "Poprawka Denninga i Sacco" w punkcie 2 posiadają strzałki skierowaną w złą stronę.

**Comment by PawelBogdan** [comment]
Ma Pan rację, już poprawiłem. Dziękuję za uwagę
